name: Test JavaScript package

on: [push, pull_request]

jobs:
  build_ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4

    - name: Install dependencies for testing
      env:
        OS_NAME: ${{ matrix.os }}
      working-directory: js
      run: npm install jest

    - name: Test with jest
      env:
        OS_NAME: ${{ matrix.os }}
        CONDA_PY: ${{ matrix.python-version }}
      working-directory: js
      run: npm test

