name: Test shell script

on: [push, pull_request]

jobs:
  build_ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

      #- name: Install dependencies for testing
      #  env:
      #    OS_NAME: ${{ matrix.os }}
      #    CONDA_PY: ${{ matrix.python-version }}
      #  working-directory: rest
      #  run: pip install pytest requests

    - name: Test script
      env:
        OS_NAME: ${{ matrix.os }}
        CONDA_PY: ${{ matrix.python-version }}
      working-directory: shell
      run: |
          bash ./atlasapprox organisms
          bash ./atlasapprox organs --organism=h_sapiens

