api_version: "v1"
past_versions: []

feature_types: ['gene_expression']

paths:
  compressed_atlas:
    "m_musculus": "./static/atlas_data/tabula_muris_senis.h5"
    "h_sapiens": "./static/atlas_data/tabula_sapiens.h5"
    "m_myoxinus": "./static/atlas_data/tabula_microcebus.h5"
    "c_elegans": "./static/atlas_data/c_elegans.h5"
    "d_rerio": "./static/atlas_data/d_rerio.h5"


units:
  gene_expression: "counts per ten thousand"

pseudocount:
  gene_expression: 0.1

order:
  timepoint:
    "m_musculus": ['1m', '3m', '10m', '18m', '~19m', '21m', '24m', '30m']
    "h_sapiens": ['31wk', '3yr', '31yr', '~60yr']
    "m_myoxinus": ["10", "11"]
    "c_elegans": ["2L"]
    "d_rerio": ["24hpf"]

  dataset:
    "m_musculus": ['TMS']
    "h_sapiens": ['TS']
    "m_myoxinus": ['TMC']
    "c_elegans": ['TCE']
    "d_rerio": ['TDR']
