api_version: "v1"
past_versions: []

feature_types: ['gene_expression', 'chromatin_accessibility']

paths:
  compressed_atlas:
    "m_musculus": "./static/atlas_data/m_musculus.h5"
    "h_sapiens": "./static/atlas_data/h_sapiens.h5"
    "m_myoxinus": "./static/atlas_data/m_myoxinus.h5"
    "c_elegans": "./static/atlas_data/c_elegans.h5"
    "d_rerio": "./static/atlas_data/d_rerio.h5"
    "s_lacustris": "./static/atlas_data/s_lacustris.h5"
    "a_queenslandica": "./static/atlas_data/a_queenslandica.h5"
    "m_leidyi": "./static/atlas_data/m_leidyi.h5"
    "t_adhaerens": "./static/atlas_data/t_adhaerens.h5"
    "x_laevis": "./static/atlas_data/x_laevis.h5"
    "s_mediterranea": "./static/atlas_data/s_mediterranea.h5"

units:
  gene_expression: "counts per ten thousand"
  chromatin_accessibility: "fraction accessible"

pseudocount:
  gene_expression: 0.1
  chromatin_accessibility: 0.0001

order:
  timepoint:
    "m_musculus": ['1m', '3m', '10m', '18m', '~19m', '21m', '24m', '30m']
    "h_sapiens": ['31wk', '3yr', '31yr', '~60yr']
    "m_myoxinus": ["10", "11"]
    "c_elegans": ["2L"]
    "d_rerio": ["24hpf"]
    "s_lacustris": ["8day"]
    "a_queenslandica": ["adult"]
    "m_leidyi": ["adult"]
    "t_adhaerens": ["adult"]
    "x_laevis": ["adult"]
    "s_mediterranea": ["adult"]

  dataset:
    "m_musculus": ['TMS']
    "h_sapiens": ['TS']
    "m_myoxinus": ['TMC']
    "c_elegans": ['TCE']
    "d_rerio": ['TDR']
    "s_lacustris": ["Musser"]
    "a_queenslandica": ["SebePedro"]
    "m_leidyi": ["SebePedro"]
    "t_adhaerens": ["SebePedro"]
    "x_laevis": ["Liao"]
    "s_mediterranea": ["Plass"]
