api_version: "v1"
past_versions: []

feature_types: ['gene_expression', 'chromatin_accessibility']

paths:
  compressed_atlas:
    "a_queenslandica": "./static/atlas_data/a_queenslandica.h5"
    "c_elegans": "./static/atlas_data/c_elegans.h5"
    "d_melanogaster": "./static/atlas_data/d_melanogaster.h5"
    "d_rerio": "./static/atlas_data/d_rerio.h5"
    "h_miamia": "./static/atlas_data/h_miamia.h5"
    "h_sapiens": "./static/atlas_data/h_sapiens.h5"
    "m_leidyi": "./static/atlas_data/m_leidyi.h5"
    "m_musculus": "./static/atlas_data/m_musculus.h5"
    "m_myoxinus": "./static/atlas_data/m_myoxinus.h5"
    "s_lacustris": "./static/atlas_data/s_lacustris.h5"
    "s_mansoni": "./static/atlas_data/s_mansoni.h5"
    "s_mediterranea": "./static/atlas_data/s_mediterranea.h5"
    "t_adhaerens": "./static/atlas_data/t_adhaerens.h5"
    "x_laevis": "./static/atlas_data/x_laevis.h5"

units:
  gene_expression: "counts per ten thousand"
  chromatin_accessibility: "fraction accessible"

pseudocount:
  gene_expression: 0.1
  chromatin_accessibility: 0.0001

celltype_aliases:
  [
    ["macrophage", "phagocyte", "hemocyte"]
  ]
