api_version: "v1"
past_versions: []

feature_types: ['gene_expression', 'chromatin_accessibility']

paths:
  compressed_atlas: "./static/atlas_data"
  interactions: "./static/interactions"
  protein_embeddings: "./static/protein_embeddings/prost_embeddings.h5"

units:
  gene_expression: "counts per ten thousand"
  chromatin_accessibility: "fraction accessible"

pseudocount:
  gene_expression: 0.1
  chromatin_accessibility: 0.0001

celltype_aliases:
  [
    ["macrophage", "phagocyte", "hemocyte"]
  ]
